//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace StarCellar.Services.Apis
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial record SignInRequest
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public SignInRequest(string @accessTokenValidity, string @login, string @password)

        {

            this.Login = @login;

            this.Password = @password;

            this.AccessTokenValidity = @accessTokenValidity;

        }
        [System.Text.Json.Serialization.JsonPropertyName("login")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Login { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Password { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("accessTokenValidity")]
        public string AccessTokenValidity { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial record SignUpRequest
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public SignUpRequest(string @address, int @age, string @confirmPassword, string @email, string @fullName, string @password, string @role, string @username)

        {

            this.Email = @email;

            this.Password = @password;

            this.ConfirmPassword = @confirmPassword;

            this.FullName = @fullName;

            this.Username = @username;

            this.Age = @age;

            this.Role = @role;

            this.Address = @address;

        }
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Email { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 8)]
        public string Password { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("confirmPassword")]
        [System.ComponentModel.DataAnnotations.Required]
        public string ConfirmPassword { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("fullName")]
        [System.ComponentModel.DataAnnotations.Required]
        public string FullName { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        public string Username { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("age")]
        public int Age { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Role { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("address")]
        public string Address { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial record Tokens
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public Tokens(string @accessToken, string @refreshToken)

        {

            this.AccessToken = @accessToken;

            this.RefreshToken = @refreshToken;

        }
        [System.Text.Json.Serialization.JsonPropertyName("accessToken")]
        public string AccessToken { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("refreshToken")]
        public string RefreshToken { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial record UserDTO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public UserDTO(string @address, int @age, string @email, string @fullName, System.Guid @id, string @role, string @userName)

        {

            this.Id = @id;

            this.UserName = @userName;

            this.FullName = @fullName;

            this.Email = @email;

            this.Age = @age;

            this.Role = @role;

            this.Address = @address;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public System.Guid Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("userName")]
        [System.ComponentModel.DataAnnotations.Required]
        public string UserName { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("fullName")]
        [System.ComponentModel.DataAnnotations.Required]
        public string FullName { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Email { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("age")]
        public int Age { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Role { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("address")]
        public string Address { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial record WineDTO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public WineDTO(string @description, System.Guid @id, string @imageUrl, string @name, System.Guid @ownerId, int @score, int @stock)

        {

            this.Id = @id;

            this.Name = @name;

            this.Description = @description;

            this.ImageUrl = @imageUrl;

            this.Stock = @stock;

            this.Score = @score;

            this.OwnerId = @ownerId;

        }
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public System.Guid Id { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("imageUrl")]
        public string ImageUrl { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("stock")]
        public int Stock { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("score")]
        public int Score { get; init; }

        [System.Text.Json.Serialization.JsonPropertyName("ownerId")]
        public System.Guid OwnerId { get; init; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.3.0))")]
    public partial class FileParameter
    {
        public FileParameter(System.IO.Stream data)
            : this (data, null, null)
        {
        }

        public FileParameter(System.IO.Stream data, string fileName)
            : this (data, fileName, null)
        {
        }

        public FileParameter(System.IO.Stream data, string fileName, string contentType)
        {
            Data = data;
            FileName = fileName;
            ContentType = contentType;
        }

        public System.IO.Stream Data { get; private set; }

        public string FileName { get; private set; }

        public string ContentType { get; private set; }
    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625